### ISSUE TITLE
Unknown Issue With TotalPowerPerSec()

### ISSUE THREAD

**Issue by VoidCloud04** [MrBacon470/Idle-Power#21]
Could be something with either powerCollected or Pollution

**Comment by linearaccelerator** [comment]
this issue might be caused by [IdleGame.cs:210-217](https://github.com/MrBacon470/Idle-Power/blob/master/Assets/Scripts/IdleGame.cs#L210-L217)

**Comment by linearaccelerator** [comment]
update: it might also be something related to [PollutionManager.cs:40](https://github.com/MrBacon470/Idle-Power/blob/master/Assets/Scripts/PollutionManager.cs#L40)

**Comment by VoidCloud04** [comment]
IdleGame.cs:210-217 
I have always had issues with this may most likely be the source

**Comment by VoidCloud04** [comment]
I don't think its PollutionManager.cs:40
because that's how it calculates the percent and that always works correctly its even used in the text

**Comment by linearaccelerator** [comment]
yeah, i said "might"

**Comment by VoidCloud04** [comment]
I know I coulda sworn I got rid of the negative problem but I might be able to fix this very easily

**Comment by VoidCloud04** [comment]
Closed for now
