### ISSUE TITLE
0 power without buying anything

### ISSUE THREAD

**Issue by Cr1ms0nC0de** [MrBacon470/Idle-Power#29]
if you activate the console without buying any generators, you end up with -levels if you hit buy all, also I think if you turn it off you just can't buy anything either, stops at lvl -220

![issue1](https://user-images.githubusercontent.com/72949393/97233541-1e4bd780-17ad-11eb-9298-8d421edc70ed.PNG)

**Comment by VoidCloud04** [comment]
Yes I acknowledge this issue has been here for a while
Since the introduction of the console I will be working on a fix for v1.2.1
You can easily fix the problem by turning of the console and Starting a challenge
